@ExternalAuth_HostAddress = http://localhost:5025

GET {{ExternalAuth_HostAddress}}/api/auth/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJyb3NhZG9qb3NlcGhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Ikpvc2VwaCBSb3NhZG8iLCJleHAiOjE3ODgyOTU3ODIsImlzcyI6Ikdvb2dsZUF1dGhBcGkiLCJhdWQiOiJHb29nbGVBdXRoQXBpQ2xpZW50In0.-vbxm8cdB22_F6aP7djzPjD3011oDoL5E86278qSvS4

###
