@host=http://localhost:5015

#################################################
# CREATE
#################################################

POST {{host}}/api/cache
Content-Type: application/json

{
  "key": "customer:1001",
  "value": "John Doe",
  "expirationMinutes": 60
}

###

#################################################
# GET
#################################################

GET {{host}}/api/cache/customer:1001

###

#################################################
# UPDATE
#################################################

PUT {{host}}/api/cache/customer:1001
Content-Type: application/json

{
  "key": "customer:1001",
  "value": "Jane Doe",
  "expirationMinutes": 120
}

###

#################################################
# GET AFTER UPDATE
#################################################

GET {{host}}/api/cache/customer:1001

###

#################################################
# LIST KEYS
#################################################

GET {{host}}/api/cache

###

#################################################
# DELETE
#################################################

DELETE {{host}}/api/cache/customer:1001

###

#################################################
# VERIFY DELETE
#################################################

GET {{host}}/api/cache/customer:1001